yarnPath: '.yarn/releases/yarn-berry.cjs'
packageExtensions:
  'ts-node@*':
    dependencies:
      '@endemolshinegroup/cosmiconfig-typescript-loader': '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      'typescript': '*'
      'cosmiconfig': '*'
