yarnPath: .yarn/releases/yarn-berry.cjs
packageExtensions:
  '@graphql-tools/url-loader@*':
    dependencies:
      '@types/ws': ^7.4.1
  'koa-better-http-proxy@*':
    dependencies:
      '@types/koa': ^2.2.0
  'tailwindcss@*':
    dependencies:
      'autoprefixer': '*'
  '@fullhuman/postcss-purgecss@*':
    dependencies:
      'postcss': '*'
