-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Account
    = Account


type AccountMutation
    = AccountMutation


type AccountQuery
    = AccountQuery


type Artist
    = Artist


type ArtistMutation
    = ArtistMutation


type ArtistQuery
    = ArtistQuery


type Auth
    = Auth


type Descriptor
    = Descriptor


type DescriptorVote
    = DescriptorVote


type Genre
    = Genre


type GenreVote
    = GenreVote


type Log
    = Log


type LoggingMutation
    = LoggingMutation


type Release
    = Release


type ReleaseDate
    = ReleaseDate


type ReleaseMutation
    = ReleaseMutation


type ReleaseQuery
    = ReleaseQuery


type Tag
    = Tag


type Track
    = Track
