-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Query exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


account :
    SelectionSet decodesTo Api.Object.AccountQuery
    -> SelectionSet decodesTo RootQuery
account object____ =
    Object.selectionForCompositeField "account" [] object____ identity


artist :
    SelectionSet decodesTo Api.Object.ArtistQuery
    -> SelectionSet decodesTo RootQuery
artist object____ =
    Object.selectionForCompositeField "artist" [] object____ identity


release :
    SelectionSet decodesTo Api.Object.ReleaseQuery
    -> SelectionSet decodesTo RootQuery
release object____ =
    Object.selectionForCompositeField "release" [] object____ identity
