[tasks.dev]
command = "cargo"
args = ["run"]
watch = true

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.start]
command = "target/release/rate-our-music"

[tasks.prod]
run_task = { name = ["build", "start"] }
