CREATE TABLE artist
(
    id       INT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   name     TEXT   NOT NULL
);

CREATE TABLE release_artist
(
    release_id      INT         REFERENCES release (id)
,   artist_id       INT         REFERENCES artist (id)
,   display_order   SMALLINT    NOT NULL
,   PRIMARY KEY (release_id, artist_id)
);

CREATE TABLE track_artist
(
    track_id        INT         REFERENCES track (id)
,   artist_id       INT         REFERENCES artist (id)
,   display_order   SMALLINT    NOT NULL
,   PRIMARY KEY (track_id, artist_id)
);
