CREATE TABLE release_type
(
    id      INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   name    TEXT    NOT NULL
);

INSERT INTO release_type (name) VALUES ('album');
INSERT INTO release_type (name) VALUES ('compilation');
INSERT INTO release_type (name) VALUES ('ep');
INSERT INTO release_type (name) VALUES ('single');
INSERT INTO release_type (name) VALUES ('mixtape');
INSERT INTO release_type (name) VALUES ('dj mix');
INSERT INTO release_type (name) VALUES ('bootleg');
INSERT INTO release_type (name) VALUES ('video');

CREATE TABLE release
(
    id                  INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   release_type_id     INT         NOT NULL REFERENCES release_type (id)
,   title               TEXT        NOT NULL
,   release_date_year   SMALLINT
,   release_date_month  SMALLINT
,   release_date_day    SMALLINT
,   cover_art           TEXT
);
