CREATE TYPE log_environment as ENUM (
    'DEVELOPMENT', 'PRODUCTION', 'UNKNOWN'
);

CREATE TYPE log_level as ENUM (
    'CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG'
);

CREATE TABLE log
(
    log_id          INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   log_scope       TEXT            NOT NULL
,   log_environment log_environment NOT NULL
,   log_level       log_level       NOT NULL
,   log_message     TEXT            NOT NULL
,   log_data        TEXT
);