CREATE TYPE role as ENUM (
    'DEV'
);

CREATE TABLE account
(
    account_id  INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   username    TEXT        NOT NULL UNIQUE
,   password    TEXT        NOT NULL
,   roles       role[]
);

CREATE TYPE release_type AS ENUM (
    'ALBUM', 'COMPILATION', 'EP', 'SINGLE', 'MIXTAPE', 'DJ_MIX', 'BOOTLEG', 'VIDEO'
);

CREATE TABLE release
(
    release_id          INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   release_title       TEXT            NOT NULL
,   release_date_year   SMALLINT
,   release_date_month  SMALLINT
,   release_date_day    SMALLINT
,   release_type        release_type    NOT NULL
);

CREATE TABLE track
(
    track_id            INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   release_id          INT         NOT NULL
,   track_title         TEXT        NOT NULL
,   track_num           SMALLINT    NOT NULL
,   track_duration_ms   INT
,   UNIQUE (release_id, track_num)
);

CREATE TABLE artist
(
    artist_id       INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   artist_name     TEXT        NOT NULL
);

CREATE TABLE release_artist
(
    release_id              INT         REFERENCES release (release_id)
,   artist_id               INT         REFERENCES artist (artist_id)
,   release_artist_order    SMALLINT    NOT NULL
,   PRIMARY KEY (release_id, artist_id)
);

CREATE TABLE track_artist
(
    track_id            INT         REFERENCES track (track_id)
,   artist_id           INT         REFERENCES artist (artist_id)
,   track_artist_order  SMALLINT    NOT NULL
,   PRIMARY KEY (track_id, artist_id)
);

CREATE TABLE genre
(
    genre_id            INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   genre_parent_id     INT         REFERENCES genre (genre_id)
,   genre_name          TEXT        NOT NULL
,   genre_description   TEXT
);

CREATE TYPE release_genre_vote_type AS ENUM (
    'PRIMARY', 'SECONDARY'
);

CREATE TABLE release_genre_vote
(
    account_id                  INT                     REFERENCES account (account_id)
,   release_id                  INT                     REFERENCES release (release_id)
,   genre_id                    INT                     REFERENCES genre (genre_id)
,   release_genre_vote_value    SMALLINT                NOT NULL
,   release_genre_vote_type     release_genre_vote_type NOT NULL
,   PRIMARY KEY (account_id, release_id, genre_id, release_genre_vote_type)
);

CREATE TABLE descriptor
(
    descriptor_id           INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   descriptor_parent_id    INT         REFERENCES descriptor (descriptor_id)
,   descriptor_name         TEXT        NOT NULL
,   descriptor_description  TEXT
,   descriptor_is_graded    BOOLEAN     NOT NULL
);

CREATE TABLE release_descriptor_vote
(
    account_id                      INT     REFERENCES account (account_id)
,   release_id                      INT     REFERENCES release (release_id)
,   descriptor_id                   INT     REFERENCES descriptor (descriptor_id)
,   release_descriptor_vote_value   SMALLINT    NOT NULL
,   PRIMARY KEY (account_id, release_id, descriptor_id)
);

CREATE TABLE tag
(
    tag_id          INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   account_id      INT         NOT NULL REFERENCES account (account_id)
,   tag_name        TEXT        NOT NULL
,   tag_description TEXT
,   UNIQUE (account_id, tag_name)
);

CREATE TABLE release_tag
(
    release_id  INT         REFERENCES release (release_id)
,   tag_id      INT         REFERENCES tag (tag_id)
,   PRIMARY KEY (release_id, tag_id)
);

CREATE TABLE release_review
(
    release_review_id       INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   release_id              INT         REFERENCES release (release_id)
,   account_id              INT         REFERENCES account (account_id)
,   release_review_rating   SMALLINT
,   release_review_text     TEXT
,   UNIQUE (release_id, account_id)
);

CREATE TABLE track_review
(
    track_review_id     INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   track_id            INT         REFERENCES track (track_id)
,   account_id          INT         REFERENCES account (account_id)
,   track_review_rating SMALLINT
,   track_review_text   TEXT
,   UNIQUE (track_id, account_id)
);
