CREATE TABLE release_review
(
    id          INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   release_id  INT         NOT NULL REFERENCES release (id)
,   account_id  INT         NOT NULL REFERENCES account (id)
,   rating      SMALLINT
,   text        TEXT
,   UNIQUE (release_id, account_id)
);

CREATE TABLE track_review
(
    id          INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   track_id    INT         NOT NULL REFERENCES track (id)
,   account_id  INT         NOT NULL REFERENCES account (id)
,   rating      SMALLINT
,   text        TEXT
,   UNIQUE (track_id, account_id)
);