CREATE TABLE track
(
    id              INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   release_id      INT         NOT NULL
,   title           TEXT        NOT NULL
,   track_num       SMALLINT    NOT NULL
,   duration_ms     INT
,   UNIQUE (release_id, track_num)
);
