CREATE TABLE account
(
    id          INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   username    TEXT        NOT NULL UNIQUE
,   password    TEXT        NOT NULL
);

CREATE TABLE account_role
(
    account_id  INT     REFERENCES account (id)
,   role_id     INT     REFERENCES role (id)
,   PRIMARY KEY (account_id, role_id)
);
