CREATE TABLE genre
(
    id              INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
,   parent_id       INT     REFERENCES genre (id)
,   name            TEXT    NOT NULL
,   description     TEXT
);

CREATE TABLE release_genre_vote
(
    account_id  INT         REFERENCES account (id)
,   release_id  INT         REFERENCES release (id)
,   genre_id    INT         REFERENCES genre (id)
,   value       SMALLINT    NOT NULL
,   PRIMARY KEY (account_id, release_id, genre_id)
);

CREATE TABLE track_genre_vote
(
    account_id  INT         REFERENCES account (id)
,   track_id    INT         REFERENCES release (id)
,   genre_id    INT         REFERENCES genre (id)
,   value       SMALLINT    NOT NULL
,   PRIMARY KEY (account_id, track_id, genre_id)
);
