-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ArtistMutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias CreateRequiredArguments =
    { name : String }


create :
    CreateRequiredArguments
    -> SelectionSet decodesTo Api.Object.Artist
    -> SelectionSet decodesTo Api.Object.ArtistMutation
create requiredArgs____ object____ =
    Object.selectionForCompositeField "create" [ Argument.required "name" requiredArgs____.name Encode.string ] object____ identity
