-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Descriptor exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.Descriptor
id =
    Object.selectionForField "Int" "id" [] Decode.int


parent :
    SelectionSet decodesTo Api.Object.Descriptor
    -> SelectionSet (Maybe decodesTo) Api.Object.Descriptor
parent object____ =
    Object.selectionForCompositeField "parent" [] object____ (identity >> Decode.nullable)


name : SelectionSet String Api.Object.Descriptor
name =
    Object.selectionForField "String" "name" [] Decode.string


description : SelectionSet (Maybe String) Api.Object.Descriptor
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


isGraded : SelectionSet Bool Api.Object.Descriptor
isGraded =
    Object.selectionForField "Bool" "isGraded" [] Decode.bool
