-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.GenreVote exposing (..)

import Api.Enum.GenreVoteType
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


account :
    SelectionSet decodesTo Api.Object.Account
    -> SelectionSet decodesTo Api.Object.GenreVote
account object____ =
    Object.selectionForCompositeField "account" [] object____ identity


release :
    SelectionSet decodesTo Api.Object.Release
    -> SelectionSet decodesTo Api.Object.GenreVote
release object____ =
    Object.selectionForCompositeField "release" [] object____ identity


genre :
    SelectionSet decodesTo Api.Object.Genre
    -> SelectionSet decodesTo Api.Object.GenreVote
genre object____ =
    Object.selectionForCompositeField "genre" [] object____ identity


value : SelectionSet Int Api.Object.GenreVote
value =
    Object.selectionForField "Int" "value" [] Decode.int


voteType : SelectionSet Api.Enum.GenreVoteType.GenreVoteType Api.Object.GenreVote
voteType =
    Object.selectionForField "Enum.GenreVoteType.GenreVoteType" "voteType" [] Api.Enum.GenreVoteType.decoder
