-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Log exposing (..)

import Api.Enum.LogEnvironment
import Api.Enum.LogLevel
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.Log
id =
    Object.selectionForField "Int" "id" [] Decode.int


scope : SelectionSet String Api.Object.Log
scope =
    Object.selectionForField "String" "scope" [] Decode.string


environment : SelectionSet Api.Enum.LogEnvironment.LogEnvironment Api.Object.Log
environment =
    Object.selectionForField "Enum.LogEnvironment.LogEnvironment" "environment" [] Api.Enum.LogEnvironment.decoder


level : SelectionSet Api.Enum.LogLevel.LogLevel Api.Object.Log
level =
    Object.selectionForField "Enum.LogLevel.LogLevel" "level" [] Api.Enum.LogLevel.decoder


message : SelectionSet String Api.Object.Log
message =
    Object.selectionForField "String" "message" [] Decode.string
