-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.LoggingMutation exposing (..)

import Api.Enum.LogEnvironment
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias ErrorsRequiredArguments =
    { scope : String
    , environment : Api.Enum.LogEnvironment.LogEnvironment
    , errors : List Api.InputObject.ErrorInput
    }


errors :
    ErrorsRequiredArguments
    -> SelectionSet decodesTo Api.Object.Log
    -> SelectionSet (List decodesTo) Api.Object.LoggingMutation
errors requiredArgs____ object____ =
    Object.selectionForCompositeField "errors" [ Argument.required "scope" requiredArgs____.scope Encode.string, Argument.required "environment" requiredArgs____.environment (Encode.enum Api.Enum.LogEnvironment.toString), Argument.required "errors" requiredArgs____.errors (Api.InputObject.encodeErrorInput |> Encode.list) ] object____ (identity >> Decode.list)
