-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Release exposing (..)

import Api.Enum.GenreVoteType
import Api.Enum.ReleaseType
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.Release
id =
    Object.selectionForField "Int" "id" [] Decode.int


title : SelectionSet String Api.Object.Release
title =
    Object.selectionForField "String" "title" [] Decode.string


releaseDate :
    SelectionSet decodesTo Api.Object.ReleaseDate
    -> SelectionSet (Maybe decodesTo) Api.Object.Release
releaseDate object____ =
    Object.selectionForCompositeField "releaseDate" [] object____ (identity >> Decode.nullable)


releaseType : SelectionSet Api.Enum.ReleaseType.ReleaseType Api.Object.Release
releaseType =
    Object.selectionForField "Enum.ReleaseType.ReleaseType" "releaseType" [] Api.Enum.ReleaseType.decoder


artists :
    SelectionSet decodesTo Api.Object.Artist
    -> SelectionSet (List decodesTo) Api.Object.Release
artists object____ =
    Object.selectionForCompositeField "artists" [] object____ (identity >> Decode.list)


tracks :
    SelectionSet decodesTo Api.Object.Track
    -> SelectionSet (List decodesTo) Api.Object.Release
tracks object____ =
    Object.selectionForCompositeField "tracks" [] object____ (identity >> Decode.list)


type alias GenresRequiredArguments =
    { voteType : Api.Enum.GenreVoteType.GenreVoteType }


genres :
    GenresRequiredArguments
    -> SelectionSet decodesTo Api.Object.Genre
    -> SelectionSet (List decodesTo) Api.Object.Release
genres requiredArgs____ object____ =
    Object.selectionForCompositeField "genres" [ Argument.required "voteType" requiredArgs____.voteType (Encode.enum Api.Enum.GenreVoteType.toString) ] object____ (identity >> Decode.list)


genreVotes :
    SelectionSet decodesTo Api.Object.GenreVote
    -> SelectionSet (List decodesTo) Api.Object.Release
genreVotes object____ =
    Object.selectionForCompositeField "genreVotes" [] object____ (identity >> Decode.list)


descriptorVotes :
    SelectionSet decodesTo Api.Object.DescriptorVote
    -> SelectionSet (List decodesTo) Api.Object.Release
descriptorVotes object____ =
    Object.selectionForCompositeField "descriptorVotes" [] object____ (identity >> Decode.list)


tags :
    SelectionSet decodesTo Api.Object.Tag
    -> SelectionSet (List decodesTo) Api.Object.Release
tags object____ =
    Object.selectionForCompositeField "tags" [] object____ (identity >> Decode.list)
