-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ReleaseMutation exposing (..)

import Api.Enum.ReleaseType
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias CreateRequiredArguments =
    { title : String
    , releaseType : Api.Enum.ReleaseType.ReleaseType
    , artists : List Api.InputObject.ArtistInput
    }


create :
    CreateRequiredArguments
    -> SelectionSet decodesTo Api.Object.Release
    -> SelectionSet decodesTo Api.Object.ReleaseMutation
create requiredArgs____ object____ =
    Object.selectionForCompositeField "create" [ Argument.required "title" requiredArgs____.title Encode.string, Argument.required "releaseType" requiredArgs____.releaseType (Encode.enum Api.Enum.ReleaseType.toString), Argument.required "artists" requiredArgs____.artists (Api.InputObject.encodeArtistInput |> Encode.list) ] object____ identity
