-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ReleaseQuery exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias GetOneRequiredArguments =
    { id : Int }


getOne :
    GetOneRequiredArguments
    -> SelectionSet decodesTo Api.Object.Release
    -> SelectionSet decodesTo Api.Object.ReleaseQuery
getOne requiredArgs____ object____ =
    Object.selectionForCompositeField "getOne" [ Argument.required "id" requiredArgs____.id Encode.int ] object____ identity
