-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Tag exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.Tag
id =
    Object.selectionForField "Int" "id" [] Decode.int


account :
    SelectionSet decodesTo Api.Object.Account
    -> SelectionSet decodesTo Api.Object.Tag
account object____ =
    Object.selectionForCompositeField "account" [] object____ identity


name : SelectionSet String Api.Object.Tag
name =
    Object.selectionForField "String" "name" [] Decode.string


description : SelectionSet (Maybe String) Api.Object.Tag
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)
