-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Track exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.Track
id =
    Object.selectionForField "Int" "id" [] Decode.int


release :
    SelectionSet decodesTo Api.Object.Release
    -> SelectionSet decodesTo Api.Object.Track
release object____ =
    Object.selectionForCompositeField "release" [] object____ identity


title : SelectionSet String Api.Object.Track
title =
    Object.selectionForField "String" "title" [] Decode.string


num : SelectionSet Int Api.Object.Track
num =
    Object.selectionForField "Int" "num" [] Decode.int


durationMs : SelectionSet (Maybe Int) Api.Object.Track
durationMs =
    Object.selectionForField "(Maybe Int)" "durationMs" [] (Decode.int |> Decode.nullable)


artists :
    SelectionSet decodesTo Api.Object.Artist
    -> SelectionSet (List decodesTo) Api.Object.Track
artists object____ =
    Object.selectionForCompositeField "artists" [] object____ (identity >> Decode.list)
