-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.GenreVoteType exposing (..)

import Json.Decode as Decode exposing (Decoder)


type GenreVoteType
    = Primary
    | Secondary


list : List GenreVoteType
list =
    [ Primary, Secondary ]


decoder : Decoder GenreVoteType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "PRIMARY" ->
                        Decode.succeed Primary

                    "SECONDARY" ->
                        Decode.succeed Secondary

                    _ ->
                        Decode.fail ("Invalid GenreVoteType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : GenreVoteType -> String
toString enum____ =
    case enum____ of
        Primary ->
            "PRIMARY"

        Secondary ->
            "SECONDARY"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe GenreVoteType
fromString enumString____ =
    case enumString____ of
        "PRIMARY" ->
            Just Primary

        "SECONDARY" ->
            Just Secondary

        _ ->
            Nothing
